// shopping card
export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_ONE_FROM_CART='REMOVE_ONE_FROM_CART'
export const REMOVE_ALL_FROM_CART='REMOVE_ALL_FROM_CART'
export const CLEAR_CART='CLEAR_CART'

// user
export const SET_USER='SET_USER'

export const SET_SHIPPINGDATA='SET_SHIPPINGDATA'

export const SET_PAYMENT_MESSAGE="SET_PAYMENT_MESSAGE"